services:
  - type: web
    name: corechat
    runtime: python
    plan: free
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: gunicorn -k geventwebsocket.gunicorn.workers.GeventWebSocketWorker -w 1 app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.14.3
      - key: PORT
        value: 8550
      - key: PYTHONUNBUFFERED
        value: "true"
    healthCheckPath: /